### PR TITLE
Bug 1290737 - Simplify SHA1 handling in bouncer

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Comment by oremj** [comment]
Have the necessary aliases already been added to production? Is there anything else that needs to happen before this goes live?

**Comment by rail** [comment]
Yup this is the current status:
```
firefox-esr-sha1	Firefox-38.5.1esr-ssl
firefox-sha1	Firefox-43.0.1-ssl
firefox-beta-sha1	Firefox-44.0b1-ssl
```

**Comment by oremj** [comment]
This does make one big change in that it only allows XP users to download the very latest versions, where before they could download older versions. I don't really think this is a probably, since they can still download older versions directly from archive.

**Comment by oremj** [comment]
r+

**Pull request merged**
