### PR TITLE
Add dogstatd integration

### LINKED ISSUE #14: Datadog integration
Add option for datadog (statsd) integration.

`bouncer.download` counter with tags: `product`, `os`, `language`.

### PR DESCRIPTION
**Pull request by oremj**
Adds optional dogstatsd counter increment on each successful redirect.

Fixes #14

### CODE REVIEW

**Comment by oremj** [comment]
@mostlygeek r?

**Comment by mostlygeek** [comment]
Code looks good. I have a few questions before R+

- why flush godspeed with a single goroutine? Each web call runs in its own goroutine already so doing it synchronously after the web call seems to be alright. Plus it is UDP, the system will fire/forget and even if it blocks it won't be for very long. 

- openresty caches responses so this will only report when cache is invalid. Is that ok?

**Comment by oremj** [comment]
1) The handler won't close the connection until ServeHTTP finishes, so I wanted to make sure that wasn't blocking on dogstatsd. I did some testing and was able to block the udp calls for quite a while.

2) Yeah, that part is unfortunate.

**Comment by mostlygeek** [comment]
Thanks. Good to know for posterity. R+

For #2, 

Some food for thought: 

- no nginx, cache in golang
  - use memcache/redis on `localhost`
  - use (groupcache)[https://github.com/golang/groupcache] (not sure about this)
- explore the nginx `post_action
  - (example)[http://www.tipstuff.org/2012/08/Nginx-post-action-to-trigger-successfully-download-file.html]
  - removed from nginx docs, not a good sign ;)
- ???

**Pull request closed without merging**
