### PR TITLE
winxp: add additional aliases and add beta-latest test

### PR DESCRIPTION
**Pull request by m8ttyB**
Add some additional alias checks for the winxp tests.
Also segmented out the `beta-latest` check since it's now a moving target.

/cc @stephendonner

### CODE REVIEW

**Comment by stephendonner** [comment]
Hrm, I'm getting 4-5 failures (consistently in that range) when I run against staging: http://dpaste.com/3D4YT14

**Comment by stephendonner** [comment]
@oremj / @m8ttyB are we expecting those failures?

**Comment by m8ttyB** [comment]
@stephendonner sorry, my fault. I had meant to add a note about that. The tests are currently tuned to work on prod. Some of the aliases on stage need to be sync'd with their prod equivalents.

**Comment by stephendonner** [comment]
Thanks, that's indeed the missing piece.

Passes now: http://dpaste.com/16XRYV3

r+

**Comment by m8ttyB** [comment]
r+'s all around -- thanks guys -- merging

**Pull request merged**
