### PR TITLE
Don't attribute msix downloads

### PR DESCRIPTION
**Pull request by bhearsum**

### CODE REVIEW

**Comment by bhearsum** [comment]
@jbuck, @moz-astults, @dlactin - I'm told one of you three might be the appropriate person to look at this with oremj gone.

**Review by moz-astults — APPROVED** [review]
@bhearsum LGTM - when do you want this deployed?

**Comment by bhearsum** [comment]
At your convenience :). This week is probably a good time though, as we're shipping 93 next week.

**Review by dlactin — APPROVED** [review]
Looks good.

**Pull request merged**
