### PR TITLE
Allow osx to be attributable

### LINKED ISSUE #351: Add support for macOS attribution data
See: https://docs.google.com/document/d/1NLobogbVfSYofcm7b61tesTirlXpmxwIRYd6Gsd3tt8/edit#heading=h.xrdvvhrlt660

### PR DESCRIPTION
**Pull request by hneiva**
Fixes #351

### CODE REVIEW

**Review by willdurand — APPROVED** [review]
Looks good, thanks!

**Comment by bhearsum** [comment]
@willdurand - I assume we need to avoid deploying this until the attribution service is ready to handle it? (And presumably we've gone through QA?)

**Comment by bhearsum** [comment]
> I think deploying this is OK, assuming that bedrock doesn't send in requests?

Ah, indeed. Thanks!

**Comment by willdurand** [comment]
First step would be to get that deployed to -dev... I think I filed a ticket a while ago to get auto-deploys to -dev on the main branch but that isn't done yet.

Second step would be to do a deploy to stage and prod with the code that's already living on prod (supposedly) because we haven't deployed this app in a while.

Assuming both steps above are OK, we'll be able to _safely_ push this patch to prod.

**Pull request merged**
